### ISSUE TITLE
Ошибка Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by DavidKsaw** [laker-ls/yii2-nested-set-menu#1]
Откуда берется переменная $categorys ?

**Comment by laker-ls** [comment]
В $categorys передается объект, который должен содержать в себе выборку из таблицы с пунктами меню. Обязательными полями в таблице являются: id, lft, rgt, lvl, name, url.
Пример:
$categorys = app\models\Category::find()->select(['id', 'lft', 'rgt', 'lvl', 'name', 'url'])->all();
